# Site settings
email: extension.institucional@madrid.es
description: >
  Software libre para participación ciudadana. Inteligencia colectiva y democracia directa digital para ciudades inteligentes. Abriendo gobiernos.
baseurl: ""
url: "http://www.decide.es/"
twitter_username: consul_dev
github_username:  consul

# Build settings
markdown: kramdown
